apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      containers:
        - name: api-test-k8s
          image: tuanhuu3264/api-test-k8s:latest
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              value: localhost
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: tuanhuu3264
            - name: DB_PASSWORD
              value: "@1234"
            - name: DB_NAME
              value: test

        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: tuanhuu3264
            - name: POSTGRES_PASSWORD
              value: "@1234"
            - name: POSTGRES_DB
              value: test
          volumeMounts:
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d/

      volumes:
        - name: db-init
          configMap:
            name: db-init-script
