apiVersion: v1
kind: Service
metadata:
  name: "{{ include "my-app.fullname" . }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: "{{ include "my-app.name" . }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
